apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  
  hostPath:
    path: /mnt/data  # Path on the node where the volume is located
  storageClassName: manual

